### ISSUE TITLE
net.jzhang.powernap was not granted  this permission: android.permission.WRITE_SETTINGS

### ISSUE THREAD

**Issue by waylaidwanderer** [waylaidwanderer/PowerNapForXposed-Development#4]
FC when phone reaches low battery level:

```
 java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } in net.jzhang.powernap.BatteryReceiver@c481b12
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:892)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5463)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.SecurityException: net.jzhang.powernap was not granted  this permission: android.permission.WRITE_SETTINGS.
    at android.os.Parcel.readException(Parcel.java:1620)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
    at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)
    at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1322)
    at android.provider.Settings$System.putStringForUser(Settings.java:1697)
    at android.provider.Settings$System.putIntForUser(Settings.java:1802)
    at android.provider.Settings$System.putInt(Settings.java:1796)
    at net.jzhang.powernap.BatteryReceiver.lowBatteryModeActivate(BatteryReceiver.java:91)
    at net.jzhang.powernap.BatteryReceiver.onReceive(BatteryReceiver.java:48)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5463)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

http://forum.xda-developers.com/showpost.php?p=69290843&postcount=1942

**Comment by waylaidwanderer** [comment]
Fixed for upcoming release.
